import React, { useState } from "react";
import { View, Text, StyleSheet, ScrollView } from "react-native";
import Slider from "@react-native-community/slider";
import { Ionicons } from "@expo/vector-icons";

export default function ScenarioScreen() {
  // 🔧 Base values (from ML model – prototype)
  const basePerPlantYield = 220; // grams
  const plantCount = 500;

  // Scenario inputs
  const [irrigation, setIrrigation] = useState(4); // mm
  const [temperature, setTemperature] = useState(32); // °C

  // 🔧 Simple simulation logic (replace with backend later)
  const irrigationImpact = irrigation * 2; // +2g per mm
  const temperatureImpact = temperature > 35 ? -12 : 0;

  const perPlantScenarioYield =
    basePerPlantYield + irrigationImpact + temperatureImpact;

  const totalScenarioYieldKg =
    ((perPlantScenarioYield * plantCount) / 1000).toFixed(1);

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      
      {/* Header */}
      <Text style={styles.title}>Scenario Testing</Text>
      <Text style={styles.subtitle}>
        Simulate how changes affect daily yield
      </Text>

      {/* Result Card */}
      <View style={styles.resultCard}>
        <Text style={styles.resultLabel}>Estimated Yield (Per Plant)</Text>
        <Text style={styles.resultValue}>
          {perPlantScenarioYield} g
        </Text>

        <View style={styles.divider} />

        <Text style={styles.totalLabel}>Estimated Total Farm Yield</Text>
        <Text style={styles.totalValue}>
          {totalScenarioYieldKg} kg
        </Text>

        <Text style={styles.note}>
          Based on {plantCount} Aloe plants
        </Text>
      </View>

      {/* Irrigation Control */}
      <View style={styles.controlCard}>
        <View style={styles.controlHeader}>
          <Ionicons name="water-outline" size={22} color="#2E7D32" />
          <Text style={styles.controlTitle}>Irrigation</Text>
          <Text style={styles.controlValue}>{irrigation} mm</Text>
        </View>

        <Slider
          minimumValue={0}
          maximumValue={10}
          step={1}
          value={irrigation}
          onValueChange={setIrrigation}
          minimumTrackTintColor="#2E7D32"
          maximumTrackTintColor="#C8E6C9"
          thumbTintColor="#1B5E20"
        />
      </View>

      {/* Temperature Control */}
      <View style={styles.controlCard}>
        <View style={styles.controlHeader}>
          <Ionicons name="sunny-outline" size={22} color="#EF6C00" />
          <Text style={styles.controlTitle}>Temperature</Text>
          <Text style={styles.controlValue}>{temperature} °C</Text>
        </View>

        <Slider
          minimumValue={25}
          maximumValue={40}
          step={1}
          value={temperature}
          onValueChange={setTemperature}
          minimumTrackTintColor="#EF6C00"
          maximumTrackTintColor="#FFE0B2"
          thumbTintColor="#E65100"
        />
      </View>

      {/* Info */}
      <View style={styles.infoCard}>
        <Ionicons name="information-circle-outline" size={20} color="#388E3C" />
        <Text style={styles.infoText}>
          Scenario results are simulated using simplified rules. In production,
          predictions will be generated by the trained ML ensemble.
        </Text>
      </View>

    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6F5",
  },
  content: {
    padding: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1B5E20",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#616161",
    marginBottom: 20,
  },
  resultCard: {
    backgroundColor: "#E8F5E9",
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    marginBottom: 24,
  },
  resultLabel: {
    fontSize: 14,
    color: "#2E7D32",
  },
  resultValue: {
    fontSize: 38,
    fontWeight: "bold",
    color: "#1B5E20",
    marginVertical: 4,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#C8E6C9",
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 14,
    color: "#424242",
  },
  totalValue: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#1B5E20",
    marginVertical: 4,
  },
  note: {
    fontSize: 12,
    color: "#4E6E50",
  },
  controlCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 16,
    marginBottom: 18,
    elevation: 2,
  },
  controlHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  controlTitle: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: "#424242",
  },
  controlValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1B5E20",
  },
  infoCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    padding: 14,
    borderRadius: 14,
    elevation: 2,
  },
  infoText: {
    marginLeft: 8,
    fontSize: 13,
    color: "#424242",
    flex: 1,
  },
});
